basePath: /api/v1
definitions:
  model.FailureMsg:
    properties:
      error:
        type: string
    type: object
  model.ProposedUser:
    properties:
      CreationDate:
        type: string
      Id:
        type: integer
      Password:
        type: string
      Status:
        type: string
      UserName:
        type: string
    type: object
  model.SuccessMsg:
    properties:
      message:
        type: string
    type: object
  model.User:
    properties:
      CreationDate:
        type: string
      Id:
        type: integer
      PasswordHash:
        type: string
      Status:
        type: string
      UserName:
        type: string
    type: object
  model.UserStatusMsg:
    properties:
      message:
        type: string
      userStatus:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    name: Gary Greene
    url: https://github.com/greeneg/ipmanager
  description: A simple API for managing networks
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: IpManager API
  version: 0.0.3
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Add a new user
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.ProposedUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessMsg'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.FailureMsg'
      security:
      - BasicAuth: []
      summary: Register user
      tags:
      - user
  /user/:name:
    post:
      consumes:
      - application/json
      description: Delete a user
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessMsg'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.FailureMsg'
      security:
      - BasicAuth: []
      summary: Delete user
      tags:
      - user
  /user/:name/status:
    get:
      consumes:
      - application/json
      description: Retrieve a user's active status
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserStatusMsg'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.FailureMsg'
      security:
      - BasicAuth: []
      summary: Retrieve a user's active status. Can be either 'enabled' or 'locked'
      tags:
      - user
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
